---
# tasks file for docker

- name: Uninstall old versions - Ubuntu
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent
  become: yes
  when:
    - ansible_distribution | lower == "ubuntu"
- name: Uninstall old versions - CentOS
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent
  become: yes
  when:
    - ansible_distribution | lower == "centos"

- name: Install requirements - Ubuntu
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "software-properties-common"
      - "curl"
    state: present
    # install_recommends: False
    update_cache: True
    # cache_valid_time: "{{ docker_apt_cache_time }}"
  become: yes
  when:
    - ansible_distribution | lower == "ubuntu"

- name: Install requirements - CentOS
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  become: yes
  when:
    - ansible_distribution | lower == "centos"

- name: Add docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  become: yes
  # ignore_errors: "{{ docker_apt_ignore_key_error }}"
  when:
    - ansible_distribution | lower == "ubuntu"

- name: Add Docker repository - Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: yes
  when:
    - ansible_distribution | lower == "ubuntu"

- name: Add Docker repository - CentOS
  command: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes
  when:
    - ansible_distribution | lower == "centos"

- name: Install Docker
  package:
    name: docker-ce-18.06.1.ce
    state: present
  notify: restart docker
  become: yes

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
