---
# tasks file for docker

- name: Uninstall old versions
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Install requirements
  apt:
    name: "{{ item }}"
    state: "present"
    # install_recommends: False
    update_cache: True
    # cache_valid_time: "{{ docker_apt_cache_time }}"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "curl"

- name: Add docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  # ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker.
  package:
    name: docker-ce
    state: present
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
